services:
  tg-cf-dns-bot:
    build: .  # 使用当前目录的 Dockerfile 构建镜像
    image: ghcr.io/zcp1997/telegram-cf-dns-bot:latest  # 构建后镜像的名称
    container_name: tg-cf-dns-bot
    restart: unless-stopped
    environment:
     # Telegram Bot Token
      - TELEGRAM_TOKEN=your_telegram_token_here
        # Cloudflare API Token
      - CF_API_TOKEN=your_api_token_here
        # 允许访问的 Telegram 用户 ID（逗号分隔），第一个用户是管理员
      - ALLOWED_CHAT_IDS=123456789,987654321
        # 域名到 Zone ID 的映射（JSON 格式）
      - 'DOMAIN_ZONE_MAP=
        {
          "example.com": "zone_id_1",
          "example.org": "zone_id_2",
          "another-domain.com": "zone_id_3"
        }'