services:
  tg-cf-dns-bot:
    build: .  # 使用当前目录的 Dockerfile 构建镜像
    image: ghcr.io/zcp1997/telegram-cf-dns-bot:latest  # 构建后镜像的名称
    container_name: tg-cf-dns-bot
    restart: unless-stopped
    environment:
     # Telegram Bot Token
      - TELEGRAM_TOKEN=your_telegram_token_here
        # Cloudflare API Token
      - CF_API_TOKEN=your_api_token_here
        # 允许访问的 Telegram 用户 ID（逗号分隔），第一个用户是管理员
      - ALLOWED_CHAT_IDS=123456789,987654321
      # 可选参数：排除的域名列表（逗号分隔）
      - EXCLUDE_DOMAINS=example.com,example.org

    volumes:
      - ./src:/app/src

